language: node_js
node_js:
  - "5.11"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build

before_install:
  - rvm install 2.2.5

install:
  - gem install bundler
  - bundle check || bundle install
  - npm install -g firebase-tools

branches:
  only:
    - master

script:
  - jekyll build
  - htmlproofer ./_site

deploy:
  provider: script
  script: firebase deploy --token=${FIREBASE_API_TOKEN}
  skip_cleanup: true
  on:
    branch: master
