language: node_js
node_js:
  - "5.11"
rvm:
  - 2.2.5

branches:
  only:
    - master

before_script:
  - chmod +x ./script/cibuild
  - npm install -g firebase-tools
  - npm install -g wintersmith

script: ./script/cibuild

after_success:
  - firebase deploy --token=${FIREBASE_API_TOKEN}

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

sudo: false # route your build to the container-based infrastructure for a faster build
